### ISSUE TITLE
npm login issue

### ISSUE THREAD

**Issue by wahengchang** [geut/lerna-travis-demo#37]
I think everything is setup well , but still seeing this error. Do you have a crew about what is going wrong?
I spent few days seting up this CI/CD 

```
$ lerna publish from-git --yes --npm-client yarn --npm-tag beta
WARN deprecated --npm-tag has been renamed --dist-tag
lerna notice cli v3.10.5
lerna info ci enabled
lerna WARN Yarn's registry proxy is broken, replacing with public npm registry
lerna WARN If you don't have an npm token, you should exit and run `npm login`
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove changes before continuing.
```

#### `NPM_TOKEN`  is init on the config
![image](https://user-images.githubusercontent.com/5538753/51825992-f356fa00-2320-11e9-89db-3c778da9504c.png)

travis-ci
 - [https://travis-ci.org/wahengchang/vue-packages/jobs/485293385#L628](https://travis-ci.org/wahengchang/vue-packages/jobs/485293385#L628)

**Comment by dpaez** [comment]
Hi @wahengchang 👋 It seems like you are almost done. I've found the same issue and in my case was related to how Lerna handles their lifecycle scripts. I was thinking it was something similar to what npm or yarn does (e.g.: _preversion_, _version_, _postversion_, etc). But it's [different](https://github.com/lerna/lerna/issues/643). 

To solve that I've added one extra step, the [`lerna:postversion`](https://github.com/geut/lerna-travis-demo#changelog-1) piece. 

The problem basically is that you have uncommitted files on travis. So, you can look for that. Something is being modified inside of your ci/cd pipeline.

In this [case](https://github.com/wahengchang/vue-packages/blob/master/package.json#L10) your postversion script is the one I recommend to automatically update your changelog using [`chan`](https://github.com/geut/chan). According to your package devdeps, `chan` is missing. You should install it or remove the whole postversion part.

If you want to have a partially automated changelog 🆒 as a part of your project, you should install chan as a dev dep, then run `npx chan init`, this only needs to run once to generate a valid CHANGELOG.md file and **push** the new file. 

Hope this helps. 👍

**Comment by wahengchang** [comment]
@dpaez , i spent another morning to try out, and did all you mentioned.

the script fail in `lerna:publish`, as the reason `EUNCOMMIT Working tree has uncommitted changes`. 

I am thinking if it is a problem caused by different lerna version ? is your repo still working ?
would you mind providing the travis-ci web for reference ?

I am building a CICD for my team, to build and publish a new version on npm for each commit on master branch. Working with lerna and travis-ci is harder than I imagine.

**Comment by dpaez** [comment]
Hi @wahengchang. [This](https://travis-ci.com/geut/lerna-travis-demo/jobs/157289725/config) is the travis-ci web output/config for one of our last releases. Check it out.

I don't think different lerna versions are the problem since we are on the same major number.

I think the Travis script part should only run a few commands, like `lerna:publish`. This one will trigger others.
Also, how are you starting the procedure? I mean, according to the info [provided on this test repo](https://github.com/geut/lerna-travis-demo#usage-1),  one first run `yarn run lerna:version` this creates a tagged commit and push it to the repo. Travis then detects this tagged commit (thanks to the `tags: true` config) and starts the 2nd part, the publish one.

**Comment by wahengchang** [comment]
I am digging into `A. Fully "automatic"` part.

my work flow: 
 - 1. push new commit on master
 - 2. create pull request master -> release
 - 3. merge
 - 4. triggering travis-ci to (1. auto tag 2.push to npm)

I did all the same as the repo you provided (copy paste `package.json` and `.travis.yml`), is it the right way?

**Comment by dpaez** [comment]
Ok, I thought you were trying to use the other workflow ("half & half"). Take a look on [this package.json](https://github.com/geut/lerna-travis-demo/blob/fully-auto/package.json) (branch: fully-auto).

You will see that the version script does not call the `lerna:postversion` hook. 
I think that will help you. 👍

**Comment by dpaez** [comment]
Hi @wahengchang, have you made some progress with this?

**Comment by dpaez** [comment]
I'm closing this since there was no update. Feel free to re-open if the issue persists.

**Comment by wahengchang** [comment]
close it plz, i dont have a crew what is going wrong. 
i did not work on the CI/CD for few week, i will be back in the future.

thx dp :)
